### ISSUE TITLE
16. [Styling] List View

### ISSUE THREAD

**Issue by nadinda** [the-collab-lab/tcl-29-smart-shopping-list#35]

**Comment by ishimwezachee** [comment]
A user should see a well-styled responsive list of products.

AC 
1. Styling shopping list title 
2. styled search box for an item 
3. styled list of products 
4. products should have different border colors based how use purchase items
4. styled delete icon 
5. List view should contain three buttons such as,  myList, Additems and sharelist buttons with their corresponding icons. 


Desktop reference 
![Desktop_ List View](https://user-images.githubusercontent.com/43877689/131160184-b0d22574-09a8-480f-9da7-f2ad208be41b.png)

Mobile reference 


![Mobile_ List View](https://user-images.githubusercontent.com/43877689/131160830-d420c3d3-18e1-4881-a77f-6a53ebcf4861.png)
